## A Data Analysis on Health Care Dataset:

In [1]:
import numpy as np
import pandas as pd

In [22]:
## Reading Data and printing Dataset

df=pd.read_csv("healthcare_dataset.csv")
print(df)

                    Name  Age  Gender Blood Type Medical Condition  \
0          Bobby JacksOn   30    Male         B-            Cancer
1           LesLie TErRy   62    Male         A+           Obesity
2            DaNnY sMitH   76  Female         A-           Obesity
3           andrEw waTtS   28  Female         O+          Diabetes
4          adrIENNE bEll   43  Female        AB+            Cancer
...                  ...  ...     ...        ...               ...
55495  eLIZABeTH jaCkSOn   42  Female         O+            Asthma
55496         KYle pEREz   61  Female        AB-           Obesity
55497       HEATher WaNG   38  Female         B+      Hypertension
55498     JENniFER JOneS   43    Male         O-         Arthritis
55499       jAMES GARCiA   53  Female         O+         Arthritis

      Date of Admission            Doctor                      Hospital  \
0            2024-01-31     Matthew Smith               Sons and Miller
1            2019-08-20   Samantha Davies                       Kim Inc
2            2022-09-22  Tiffany Mitchell                      Cook PLC
3            2020-11-18       Kevin Wells    Hernandez Rogers and Vang,
4            2022-09-19    Kathleen Hanna                   White-White
...                 ...               ...                           ...
55495        2020-08-16     Joshua Jarvis                Jones-Thompson
55496        2020-01-23   Taylor Sullivan                  Tucker-Moyer
55497        2020-07-13    Joe Jacobs DVM  and Mahoney Johnson Vasquez,
55498        2019-05-25    Kimberly Curry      Jackson Todd and Castro,
55499        2024-04-02     Dennis Warren                Henry Sons and

      Insurance Provider  Billing Amount  Room Number Admission Type  \
0             Blue Cross    18856.281306          328         Urgent
1               Medicare    33643.327287          265      Emergency
2                  Aetna    27955.096079          205      Emergency
3               Medicare    37909.782410          450       Elective
4                  Aetna    14238.317814          458         Urgent
...                  ...             ...          ...            ...
55495         Blue Cross     2650.714952          417       Elective
55496              Cigna    31457.797307          316       Elective
55497   UnitedHealthcare    27620.764717          347         Urgent
55498           Medicare    32451.092358          321       Elective
55499              Aetna     4010.134172          448         Urgent

      Discharge Date   Medication  Test Results
0         2024-02-02  Paracetamol        Normal
1         2019-08-26    Ibuprofen  Inconclusive
2         2022-10-07      Aspirin        Normal
3         2020-12-18    Ibuprofen      Abnormal
4         2022-10-09   Penicillin      Abnormal
...              ...          ...           ...
55495     2020-09-15   Penicillin      Abnormal
55496     2020-02-01      Aspirin        Normal
55497     2020-08-10    Ibuprofen      Abnormal
55498     2019-05-31    Ibuprofen      Abnormal
55499     2024-04-29    Ibuprofen      Abnormal

[55500 rows x 15 columns]

In [17]:
#Selecting Row
df[df['Name']=="Bobby JacksOn"]

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results
0,Bobby JacksOn,30,Male,B-,Cancer,2024-01-31,Matthew Smith,Sons and Miller,Blue Cross,18856.281306,328,Urgent,2024-02-02,Paracetamol,Normal

In [18]:
#Selecting Columns
df[['Name','Gender']]

                    Name  Gender
0          Bobby JacksOn    Male
1           LesLie TErRy    Male
2            DaNnY sMitH  Female
3           andrEw waTtS  Female
4          adrIENNE bEll  Female
...                  ...     ...
55495  eLIZABeTH jaCkSOn  Female
55496         KYle pEREz  Female
55497       HEATher WaNG  Female
55498     JENniFER JOneS    Male
55499       jAMES GARCiA  Female

[55500 rows x 2 columns]

In [19]:
#checking if Data is cleaned or not
df.isnull().sum()

Name                  0
Age                   0
Gender                0
Blood Type            0
Medical Condition     0
Date of Admission     0
Doctor                0
Hospital              0
Insurance Provider    0
Billing Amount        0
Room Number           0
Admission Type        0
Discharge Date        0
Medication            0
Test Results          0
dtype: int64

In [20]:
#First Five Values
df.head()

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results
0,Bobby JacksOn,30,Male,B-,Cancer,2024-01-31,Matthew Smith,Sons and Miller,Blue Cross,18856.281306,328,Urgent,2024-02-02,Paracetamol,Normal
1,LesLie TErRy,62,Male,A+,Obesity,2019-08-20,Samantha Davies,Kim Inc,Medicare,33643.327287,265,Emergency,2019-08-26,Ibuprofen,Inconclusive
2,DaNnY sMitH,76,Female,A-,Obesity,2022-09-22,Tiffany Mitchell,Cook PLC,Aetna,27955.096079,205,Emergency,2022-10-07,Aspirin,Normal
3,andrEw waTtS,28,Female,O+,Diabetes,2020-11-18,Kevin Wells,"Hernandez Rogers and Vang,",Medicare,37909.782410,450,Elective,2020-12-18,Ibuprofen,Abnormal
4,adrIENNE bEll,43,Female,AB+,Cancer,2022-09-19,Kathleen Hanna,White-White,Aetna,14238.317814,458,Urgent,2022-10-09,Penicillin,Abnormal

In [21]:
#Last Five Values
df.tail()

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results
55495,eLIZABeTH jaCkSOn,42,Female,O+,Asthma,2020-08-16,Joshua Jarvis,Jones-Thompson,Blue Cross,2650.714952,417,Elective,2020-09-15,Penicillin,Abnormal
55496,KYle pEREz,61,Female,AB-,Obesity,2020-01-23,Taylor Sullivan,Tucker-Moyer,Cigna,31457.797307,316,Elective,2020-02-01,Aspirin,Normal
55497,HEATher WaNG,38,Female,B+,Hypertension,2020-07-13,Joe Jacobs DVM,"and Mahoney Johnson Vasquez,",UnitedHealthcare,27620.764717,347,Urgent,2020-08-10,Ibuprofen,Abnormal
55498,JENniFER JOneS,43,Male,O-,Arthritis,2019-05-25,Kimberly Curry,"Jackson Todd and Castro,",Medicare,32451.092358,321,Elective,2019-05-31,Ibuprofen,Abnormal
55499,jAMES GARCiA,53,Female,O+,Arthritis,2024-04-02,Dennis Warren,Henry Sons and,Aetna,4010.134172,448,Urgent,2024-04-29,Ibuprofen,Abnormal

In [23]:
#Info about Data
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 55500 entries, 0 to 55499
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Name                55500 non-null  str
 1   Age                 55500 non-null  int64
 2   Gender              55500 non-null  str
 3   Blood Type          55500 non-null  str
 4   Medical Condition   55500 non-null  str
 5   Date of Admission   55500 non-null  str
 6   Doctor              55500 non-null  str
 7   Hospital            55500 non-null  str
 8   Insurance Provider  55500 non-null  str
 9   Billing Amount      55500 non-null  float64
 10  Room Number         55500 non-null  int64
 11  Admission Type      55500 non-null  str
 12  Discharge Date      55500 non-null  str
 13  Medication          55500 non-null  str
 14  Test Results        55500 non-null  str
dtypes: float64(1), int64(2), str(12)
memory usage: 6.4 MB

In [ ]:
#Datatypes
df.dtypes

Name                      str
Age                     int64
Gender                    str
Blood Type                str
Medical Condition         str
Date of Admission         str
Doctor                    str
Hospital                  str
Insurance Provider        str
Billing Amount        float64
Room Number             int64
Admission Type            str
Discharge Date            str
Medication                str
Test Results              str
dtype: object

In [30]:
#Coverting Billing Amout float into int
# Converting Billing Amount float into int
df['Billing Amount'] = pd.to_numeric(
    df['Billing Amount'], errors='coerce'
).round().astype('Int64')

df.dtypes
df.dtypes

Name                    str
Age                   int64
Gender                  str
Blood Type              str
Medical Condition       str
Date of Admission       str
Doctor                  str
Hospital                str
Insurance Provider      str
Billing Amount        Int64
Room Number           int64
Admission Type          str
Discharge Date          str
Medication              str
Test Results            str
dtype: object

In [ ]:
#Unique Values In medical conditions Column
df['Medical Condition'].unique()

<StringArray>
['Cancer', 'Obesity', 'Diabetes', 'Asthma', 'Hypertension', 'Arthritis']
Length: 6, dtype: str

In [32]:
#Unique in Number
df['Medical Condition'].nunique()

6

In [33]:
#cerate a new Dataframe patients that contains only the columns Name, Age , 
#Medical condition and Billing

patients = df[['Name','Age','Medical Condition','Billing Amount']]
print(patients)

                    Name  Age Medical Condition  Billing Amount
0          Bobby JacksOn   30            Cancer           18856
1           LesLie TErRy   62           Obesity           33643
2            DaNnY sMitH   76           Obesity           27955
3           andrEw waTtS   28          Diabetes           37910
4          adrIENNE bEll   43            Cancer           14238
...                  ...  ...               ...             ...
55495  eLIZABeTH jaCkSOn   42            Asthma            2651
55496         KYle pEREz   61           Obesity           31458
55497       HEATher WaNG   38      Hypertension           27621
55498     JENniFER JOneS   43         Arthritis           32451
55499       jAMES GARCiA   53         Arthritis            4010

[55500 rows x 4 columns]

In [35]:
#Medical Condition is diabetes and Age is greater than 50

df[(df['Medical Condition']=='Diabetes') & (df['Age']>50)]

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results
12,connOR HANsEn,75,Female,A+,Diabetes,2019-12-12,Kenneth Fletcher,"Powers Miller, and Flores",Cigna,43282,134,Emergency,2019-12-28,Penicillin,Abnormal
38,NIcOlE LUcErO,70,Female,O-,Diabetes,2022-03-12,Christine Johnson,"and Garcia Morris Cunningham,",Cigna,48291,113,Emergency,2022-03-29,Lipitor,Abnormal
47,CHRis fRYe,58,Male,A-,Diabetes,2020-05-04,Heather Smith,Nelson-Phillips,Cigna,36992,413,Urgent,2020-05-13,Aspirin,Normal
66,ChRiStOPhER gOnzAlez,59,Male,B+,Diabetes,2019-11-21,Patricia Dunn,Rhodes-Carey,Medicare,10107,368,Emergency,2019-12-08,Penicillin,Abnormal
82,SeaN jenniNGs,80,Female,AB-,Diabetes,2023-11-12,James Tucker,Clark-Johnson,Blue Cross,20258,255,Elective,2023-12-12,Penicillin,Abnormal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55409,WEslEY BarkEr,58,Male,O+,Diabetes,2020-06-22,Jonathan Cabrera,Long LLC,Cigna,44242,324,Urgent,2020-07-05,Ibuprofen,Normal
55416,GrEG Bush,67,Male,B-,Diabetes,2021-09-26,Joshua Davis,Ltd Cox,Cigna,16097,483,Emergency,2021-10-12,Paracetamol,Abnormal
55420,SteVeN knoX,52,Female,A-,Diabetes,2023-08-12,Alicia Garcia,Molina-Phelps,UnitedHealthcare,5271,379,Elective,2023-08-24,Ibuprofen,Inconclusive
55433,RonALd OBRIeN jr.,72,Female,B+,Diabetes,2019-11-16,John Singh,"Hunter and Mckenzie, Parsons",Aetna,13959,462,Urgent,2019-12-06,Lipitor,Abnormal
55439,cHRiStINE MCCARty,75,Male,AB+,Diabetes,2024-04-28,Gregory Pineda,Wu-Stark,Aetna,23720,313,Emergency,2024-05-19,Penicillin,Abnormal

In [55]:
#duplicate Values
df[df.duplicated()]
df=df.drop_duplicates()


#delete all negative billing values
df=df[df['Billing Amount']>=0]
print(df)

                    Name  Age  Gender Blood Type Medical Condition  \
0          Bobby JacksOn   30    Male         B-            Cancer
1           LesLie TErRy   62    Male         A+           Obesity
2            DaNnY sMitH   76  Female         A-           Obesity
3           andrEw waTtS   28  Female         O+          Diabetes
4          adrIENNE bEll   43  Female        AB+            Cancer
...                  ...  ...     ...        ...               ...
55495  eLIZABeTH jaCkSOn   42  Female         O+            Asthma
55496         KYle pEREz   61  Female        AB-           Obesity
55497       HEATher WaNG   38  Female         B+      Hypertension
55498     JENniFER JOneS   43    Male         O-         Arthritis
55499       jAMES GARCiA   53  Female         O+         Arthritis

      Date of Admission            Doctor                      Hospital  \
0            2024-01-31     Matthew Smith               Sons and Miller
1            2019-08-20   Samantha Davies                       Kim Inc
2            2022-09-22  Tiffany Mitchell                      Cook PLC
3            2020-11-18       Kevin Wells    Hernandez Rogers and Vang,
4            2022-09-19    Kathleen Hanna                   White-White
...                 ...               ...                           ...
55495        2020-08-16     Joshua Jarvis                Jones-Thompson
55496        2020-01-23   Taylor Sullivan                  Tucker-Moyer
55497        2020-07-13    Joe Jacobs DVM  and Mahoney Johnson Vasquez,
55498        2019-05-25    Kimberly Curry      Jackson Todd and Castro,
55499        2024-04-02     Dennis Warren                Henry Sons and

      Insurance Provider  Billing Amount  Room Number Admission Type  \
0             Blue Cross           18856          328         Urgent
1               Medicare           33643          265      Emergency
2                  Aetna           27955          205      Emergency
3               Medicare           37910          450       Elective
4                  Aetna           14238          458         Urgent
...                  ...             ...          ...            ...
55495         Blue Cross            2651          417       Elective
55496              Cigna           31458          316       Elective
55497   UnitedHealthcare           27621          347         Urgent
55498           Medicare           32451          321       Elective
55499              Aetna            4010          448         Urgent

      Discharge Date   Medication  Test Results
0         2024-02-02  Paracetamol        Normal
1         2019-08-26    Ibuprofen  Inconclusive
2         2022-10-07      Aspirin        Normal
3         2020-12-18    Ibuprofen      Abnormal
4         2022-10-09   Penicillin      Abnormal
...              ...          ...           ...
55495     2020-09-15   Penicillin      Abnormal
55496     2020-02-01      Aspirin        Normal
55497     2020-08-10    Ibuprofen      Abnormal
55498     2019-05-31    Ibuprofen      Abnormal
55499     2024-04-29    Ibuprofen      Abnormal

[54860 rows x 15 columns]

In [ ]:
#Fixing Inconsistent Date
df['Name']= df['Name'].str.title()
df.head()

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results
0,Bobby Jackson,30,Male,B-,Cancer,2024-01-31,Matthew Smith,Sons and Miller,Blue Cross,18856,328,Urgent,2024-02-02,Paracetamol,Normal
1,Leslie Terry,62,Male,A+,Obesity,2019-08-20,Samantha Davies,Kim Inc,Medicare,33643,265,Emergency,2019-08-26,Ibuprofen,Inconclusive
2,Danny Smith,76,Female,A-,Obesity,2022-09-22,Tiffany Mitchell,Cook PLC,Aetna,27955,205,Emergency,2022-10-07,Aspirin,Normal
3,Andrew Watts,28,Female,O+,Diabetes,2020-11-18,Kevin Wells,"Hernandez Rogers and Vang,",Medicare,37910,450,Elective,2020-12-18,Ibuprofen,Abnormal
4,Adrienne Bell,43,Female,AB+,Cancer,2022-09-19,Kathleen Hanna,White-White,Aetna,14238,458,Urgent,2022-10-09,Penicillin,Abnormal

In [82]:
#Date 
df['Date of Admission'] = pd.to_datetime(df['Date of Admission'])
df['Discharge Date'] = pd.to_datetime(df['Discharge Date'])

df['Length of Stay'] = (
    df['Discharge Date'] - df['Date of Admission']
).dt.days

df.head()

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results,Length of Stay,Age Group
36349,Todd Carrillo,51,Female,A+,Hypertension,2023-09-08,Kathleen Griffin,Griffin Group,Blue Cross,52764,209,Elective,2023-09-08,Ibuprofen,Normal,0,Adult
51313,Karen Kline,74,Female,AB+,Cancer,2021-06-19,Dr. Joseph Gordon,Hernandez-Morton,UnitedHealthcare,52373,181,Urgent,2021-06-19,Penicillin,Inconclusive,0,Senior
34613,Karen Kline,79,Female,AB+,Cancer,2021-06-19,Dr. Joseph Gordon,Hernandez-Morton,UnitedHealthcare,52373,181,Urgent,2021-06-19,Penicillin,Inconclusive,0,Senior
5735,David Sandoval,22,Male,AB-,Hypertension,2019-11-02,Taylor Novak,Sons and Bailey,Blue Cross,52272,228,Emergency,2019-11-02,Ibuprofen,Normal,0,Adult
7088,Kathryn Gonzales,18,Female,O+,Diabetes,2020-08-11,Kristin Clark,Miller Ltd,Aetna,52212,383,Urgent,2020-08-11,Paracetamol,Inconclusive,0,Teen

In [64]:
#Writing a funcion get_age_group(age)

def get_age_group(age):
    if age <= 12:
        return "Child"
    elif age <= 19:
        return "Teen"
    elif age <= 59:
        return "Adult"
    else:
        return "Senior"

df['Age Group']=df['Age'].apply(get_age_group)
df.head()

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results,Length of Stay,Age Group
0,Bobby Jackson,30,Male,B-,Cancer,2024-01-31,Matthew Smith,Sons and Miller,Blue Cross,18856,328,Urgent,2024-01-31,Paracetamol,Normal,0,Adult
1,Leslie Terry,62,Male,A+,Obesity,2019-08-20,Samantha Davies,Kim Inc,Medicare,33643,265,Emergency,2019-08-20,Ibuprofen,Inconclusive,0,Senior
2,Danny Smith,76,Female,A-,Obesity,2022-09-22,Tiffany Mitchell,Cook PLC,Aetna,27955,205,Emergency,2022-09-22,Aspirin,Normal,0,Senior
3,Andrew Watts,28,Female,O+,Diabetes,2020-11-18,Kevin Wells,"Hernandez Rogers and Vang,",Medicare,37910,450,Elective,2020-11-18,Ibuprofen,Abnormal,0,Adult
4,Adrienne Bell,43,Female,AB+,Cancer,2022-09-19,Kathleen Hanna,White-White,Aetna,14238,458,Urgent,2022-09-19,Penicillin,Abnormal,0,Adult

In [70]:
#Sorting on Basis of Billing Amount in descending Order

df=df.sort_values(by='Billing Amount', ascending=[False])
df.head()

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results,Length of Stay,Age Group
36349,Todd Carrillo,51,Female,A+,Hypertension,2023-09-08,Kathleen Griffin,Griffin Group,Blue Cross,52764,209,Elective,2023-09-08,Ibuprofen,Normal,0,Adult
51313,Karen Kline,74,Female,AB+,Cancer,2021-06-19,Dr. Joseph Gordon,Hernandez-Morton,UnitedHealthcare,52373,181,Urgent,2021-06-19,Penicillin,Inconclusive,0,Senior
34613,Karen Kline,79,Female,AB+,Cancer,2021-06-19,Dr. Joseph Gordon,Hernandez-Morton,UnitedHealthcare,52373,181,Urgent,2021-06-19,Penicillin,Inconclusive,0,Senior
5735,David Sandoval,22,Male,AB-,Hypertension,2019-11-02,Taylor Novak,Sons and Bailey,Blue Cross,52272,228,Emergency,2019-11-02,Ibuprofen,Normal,0,Adult
7088,Kathryn Gonzales,18,Female,O+,Diabetes,2020-08-11,Kristin Clark,Miller Ltd,Aetna,52212,383,Urgent,2020-08-11,Paracetamol,Inconclusive,0,Teen

In [ ]:
#GroupBy and Aggregation by Medical Condition the Average of Billing Amount and the average length of Stay
df.groupby('Medical Condition')['Billing Amount'].mean()

Medical Condition
Arthritis       0.0
Asthma          0.0
Cancer          0.0
Diabetes        0.0
Hypertension    0.0
Obesity         0.0
Name: Length of Stay, dtype: float64

In [83]:
df.groupby('Medical Condition')['Length of Stay'].mean()

Medical Condition
Arthritis       0.0
Asthma          0.0
Cancer          0.0
Diabetes        0.0
Hypertension    0.0
Obesity         0.0
Name: Length of Stay, dtype: float64

In [87]:
conditional_summary = df.groupby('Medical Condition').agg(
    bill_avg = ('Billing Amount','mean'),
    days_avg = ('Length of Stay','mean')
)

print(conditional_summary)

                       bill_avg  days_avg
Medical Condition
Arthritis          25542.892039       0.0
Asthma             25685.387132       0.0
Cancer             25205.921061       0.0
Diabetes           25714.322062       0.0
Hypertension       25559.850838       0.0
Obesity             25859.21409       0.0